"""initial_schema

Revision ID: 1f4a4102bde9
Revises: None
Create Date: 2026-07-14 12:54:52.270368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f4a4102bde9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='engineer', nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('engineer', 'admin')", name='chk_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='gridpilot'
    )
    op.create_table('utility_regions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('boundary_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_table('grid_nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('voltage_kv', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('thermal_limit_mva', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node_type IN ('substation', 'generator_bus', 'load_bus')", name='chk_grid_node_type'),
    sa.ForeignKeyConstraint(['region_id'], ['gridpilot.utility_regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'node_key', name='uq_grid_nodes_region_node'),
    schema='gridpilot'
    )
    op.create_index('idx_grid_nodes_region_id', 'grid_nodes', ['region_id'], unique=False, schema='gridpilot')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gridpilot.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='gridpilot'
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False, schema='gridpilot')
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False, schema='gridpilot')
    op.create_table('grid_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('from_node_id', sa.UUID(), nullable=False),
    sa.Column('to_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('length_miles', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reactance_pu', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('thermal_limit_mva', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("edge_type IN ('line', 'transformer')", name='chk_grid_edge_type'),
    sa.ForeignKeyConstraint(['from_node_id'], ['gridpilot.grid_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['gridpilot.utility_regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['gridpilot.grid_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_grid_edges_from_node', 'grid_edges', ['from_node_id'], unique=False, schema='gridpilot')
    op.create_index('idx_grid_edges_region_id', 'grid_edges', ['region_id'], unique=False, schema='gridpilot')
    op.create_index('idx_grid_edges_to_node', 'grid_edges', ['to_node_id'], unique=False, schema='gridpilot')
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('poi_node_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('technology', sa.String(), nullable=False),
    sa.Column('capacity_mw', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('storage_capacity_mw', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('aoi_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='submitted', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'in_study', 'pending_review', 'approved', 'rejected')", name='chk_project_status'),
    sa.CheckConstraint("technology IN ('solar', 'storage', 'solar_plus_storage', 'wind')", name='chk_project_technology'),
    sa.ForeignKeyConstraint(['poi_node_id'], ['gridpilot.grid_nodes.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['gridpilot.utility_regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_projects_region_id', 'projects', ['region_id'], unique=False, schema='gridpilot')
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False, schema='gridpilot')
    op.create_table('studies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='running', nullable=False),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('study_document_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_oss_key', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'pending_review', 'revision_requested', 'approved', 'rejected', 'failed')", name='chk_study_status'),
    sa.ForeignKeyConstraint(['project_id'], ['gridpilot.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_studies_project_id', 'studies', ['project_id'], unique=False, schema='gridpilot')
    op.create_index('idx_studies_state_snapshot_gin', 'studies', ['state_snapshot'], unique=False, schema='gridpilot', postgresql_using='gin')
    op.create_index('idx_studies_status', 'studies', ['status'], unique=False, schema='gridpilot')
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('qwen_model_used', sa.String(), nullable=True),
    sa.Column('qwen_input_tokens', sa.Integer(), nullable=True),
    sa.Column('qwen_output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("agent_name IN ('site_intelligence', 'environmental_permit', 'power_flow', 'cost_allocation', 'regulatory', 'orchestrator')", name='chk_agent_run_name'),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'escalated')", name='chk_agent_run_status'),
    sa.ForeignKeyConstraint(['study_id'], ['gridpilot.studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_agent_runs_agent_name', 'agent_runs', ['agent_name'], unique=False, schema='gridpilot')
    op.create_index('idx_agent_runs_study_id', 'agent_runs', ['study_id'], unique=False, schema='gridpilot')
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('agent', 'orchestrator', 'human', 'system')", name='chk_audit_actor_type'),
    sa.ForeignKeyConstraint(['project_id'], ['gridpilot.projects.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['gridpilot.studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False, schema='gridpilot')
    op.create_index('idx_audit_log_study_id', 'audit_log', ['study_id'], unique=False, schema='gridpilot')
    op.create_table('cost_allocation_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('total_estimated_cost_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('upgrades_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['gridpilot.studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_cost_allocation_results_study_id', 'cost_allocation_results', ['study_id'], unique=False, schema='gridpilot')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('oss_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('satellite_tile', 'study_pdf', 'audit_export')", name='chk_document_doc_type'),
    sa.ForeignKeyConstraint(['study_id'], ['gridpilot.studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_documents_study_id', 'documents', ['study_id'], unique=False, schema='gridpilot')
    op.create_table('environmental_flags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_dataset', sa.String(), nullable=False),
    sa.Column('geometry_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("flag_type IN ('wetland', 'habitat', 'other')", name='chk_env_flag_type'),
    sa.CheckConstraint("severity IN ('info', 'review_required', 'blocking')", name='chk_env_flag_severity'),
    sa.ForeignKeyConstraint(['study_id'], ['gridpilot.studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_environmental_flags_study_id', 'environmental_flags', ['study_id'], unique=False, schema='gridpilot')
    op.create_table('human_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('affected_section', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected', 'revision_requested', 'comment')", name='chk_human_review_decision'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['gridpilot.users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['gridpilot.studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_human_reviews_study_id', 'human_reviews', ['study_id'], unique=False, schema='gridpilot')
    op.create_table('power_flow_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('scenarios_run', sa.Integer(), nullable=False),
    sa.Column('violation_probability', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('worst_case_line_id', sa.UUID(), nullable=True),
    sa.Column('worst_case_loading_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('worst_case_bus_voltage_pu', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('raw_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['gridpilot.studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worst_case_line_id'], ['gridpilot.grid_edges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_power_flow_results_study_id', 'power_flow_results', ['study_id'], unique=False, schema='gridpilot')
    op.create_table('regulatory_citations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('source_document', sa.String(), nullable=False),
    sa.Column('chroma_chunk_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['gridpilot.studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gridpilot'
    )
    op.create_index('idx_regulatory_citations_study_id', 'regulatory_citations', ['study_id'], unique=False, schema='gridpilot')
    # 1. Idempotently create role gridpilot_runtime if current user has permissions
    op.execute(sa.text("""
        DO $$
        BEGIN
            -- Check if current user has superuser or createrole privileges
            IF EXISTS (
                SELECT 1 FROM pg_roles 
                WHERE rolname = current_user AND (rolsuper OR rolcreaterole)
            ) THEN
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gridpilot_runtime') THEN
                    CREATE ROLE gridpilot_runtime WITH LOGIN PASSWORD 'postgres_dev_password_change_me';
                END IF;
            ELSE
                RAISE WARNING 'Current database user lacks privileges to CREATE ROLE. Skipping gridpilot_runtime role creation.';
            END IF;
        END
        $$;
    """))

    # 2. Grant privileges to gridpilot_runtime (only if the role exists)
    op.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gridpilot_runtime') THEN
                GRANT USAGE ON SCHEMA gridpilot TO gridpilot_runtime;
                GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gridpilot TO gridpilot_runtime;
                REVOKE UPDATE, DELETE ON TABLE gridpilot.audit_log FROM gridpilot_runtime;
            END IF;
        END
        $$;
    """))

    # 3. Create the prevent modify trigger function on audit_log
    op.execute(sa.text("""
        CREATE OR REPLACE FUNCTION gridpilot.prevent_audit_log_modification()
        RETURNS TRIGGER AS $func$
        BEGIN
            RAISE EXCEPTION 'audit_log table is append-only and immutable. UPDATE and DELETE operations are prohibited.';
        END;
        $func$ LANGUAGE plpgsql;
    """))

    # 4. Create trigger on audit_log
    op.execute(sa.text("""
        CREATE TRIGGER trg_prevent_audit_log_modify
        BEFORE UPDATE OR DELETE ON gridpilot.audit_log
        FOR EACH ROW
        EXECUTE FUNCTION gridpilot.prevent_audit_log_modification();
    """))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop trigger on audit_log
    op.execute(sa.text("DROP TRIGGER IF EXISTS trg_prevent_audit_log_modify ON gridpilot.audit_log;"))

    # 2. Drop trigger function
    op.execute(sa.text("DROP FUNCTION IF EXISTS gridpilot.prevent_audit_log_modification();"))

    # 3. Revoke permissions and drop role gridpilot_runtime (if role exists and user has privileges)
    op.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gridpilot_runtime') THEN
                REVOKE ALL PRIVILEGES ON SCHEMA gridpilot FROM gridpilot_runtime;
                REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA gridpilot FROM gridpilot_runtime;
                
                IF EXISTS (
                    SELECT 1 FROM pg_roles 
                    WHERE rolname = current_user AND (rolsuper OR rolcreaterole)
                ) THEN
                    DROP ROLE gridpilot_runtime;
                ELSE
                    RAISE WARNING 'Current database user lacks privileges to DROP ROLE. Skipping dropping gridpilot_runtime role.';
                END IF;
            END IF;
        END
        $$;
    """))

    op.drop_index('idx_regulatory_citations_study_id', table_name='regulatory_citations', schema='gridpilot')
    op.drop_table('regulatory_citations', schema='gridpilot')
    op.drop_index('idx_power_flow_results_study_id', table_name='power_flow_results', schema='gridpilot')
    op.drop_table('power_flow_results', schema='gridpilot')
    op.drop_index('idx_human_reviews_study_id', table_name='human_reviews', schema='gridpilot')
    op.drop_table('human_reviews', schema='gridpilot')
    op.drop_index('idx_environmental_flags_study_id', table_name='environmental_flags', schema='gridpilot')
    op.drop_table('environmental_flags', schema='gridpilot')
    op.drop_index('idx_documents_study_id', table_name='documents', schema='gridpilot')
    op.drop_table('documents', schema='gridpilot')
    op.drop_index('idx_cost_allocation_results_study_id', table_name='cost_allocation_results', schema='gridpilot')
    op.drop_table('cost_allocation_results', schema='gridpilot')
    op.drop_index('idx_audit_log_study_id', table_name='audit_log', schema='gridpilot')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', schema='gridpilot')
    op.drop_table('audit_log', schema='gridpilot')
    op.drop_index('idx_agent_runs_study_id', table_name='agent_runs', schema='gridpilot')
    op.drop_index('idx_agent_runs_agent_name', table_name='agent_runs', schema='gridpilot')
    op.drop_table('agent_runs', schema='gridpilot')
    op.drop_index('idx_studies_status', table_name='studies', schema='gridpilot')
    op.drop_index('idx_studies_state_snapshot_gin', table_name='studies', schema='gridpilot', postgresql_using='gin')
    op.drop_index('idx_studies_project_id', table_name='studies', schema='gridpilot')
    op.drop_table('studies', schema='gridpilot')
    op.drop_index('idx_projects_status', table_name='projects', schema='gridpilot')
    op.drop_index('idx_projects_region_id', table_name='projects', schema='gridpilot')
    op.drop_table('projects', schema='gridpilot')
    op.drop_index('idx_grid_edges_to_node', table_name='grid_edges', schema='gridpilot')
    op.drop_index('idx_grid_edges_region_id', table_name='grid_edges', schema='gridpilot')
    op.drop_index('idx_grid_edges_from_node', table_name='grid_edges', schema='gridpilot')
    op.drop_table('grid_edges', schema='gridpilot')
    op.drop_index('idx_sessions_user_id', table_name='sessions', schema='gridpilot')
    op.drop_index('idx_sessions_expires_at', table_name='sessions', schema='gridpilot')
    op.drop_table('sessions', schema='gridpilot')
    op.drop_index('idx_grid_nodes_region_id', table_name='grid_nodes', schema='gridpilot')
    op.drop_table('grid_nodes', schema='gridpilot')
    op.drop_table('utility_regions', schema='gridpilot')
    op.drop_table('users', schema='gridpilot')
    # ### end Alembic commands ###
